version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: event-postgres
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  events-backend:
    image: events-backend
    container_name: events-backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events_db
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - event-network

  events-frontend:
    image: events-frontend
    container_name: events-frontend
    environment:
      BACKEND_HOST: events-backend
      BACKEND_PORT: 8080
    ports:
      - "8081:8081"
    networks:
      - event-network

volumes:
  postgres_data:

networks:
  event-network:
    driver: bridge
