GET http://localhost:8080/events HTTP/1.1

###

POST http://localhost:8080/events HTTP/1.1
content-type: application/json

{
    "title": "event1",
    "description": "it is event1 description",
    "image": "image-link"
}

###

DELETE http://localhost:8080/events HTTP/1.1


