apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-server
  labels:
    app: events-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: events-server
  template:
    metadata:
      labels:
        name: events-server
    spec:
      containers:
        - name: event-server
          image: askalt/vct-hw:latest
          envFrom:
            - configMapRef:
                name: postgres-secret
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
